#-------------------------------------------------------------------------------
# Name:        AStyleDiffHtml.py
# Purpose:
#
# Author:      avsolatorio
#
# Created:     19/05/2014
# Copyright:   (c) avsolatorio 2014
# Licence:     <your licence>
#-------------------------------------------------------------------------------
import re

def main():
    print "This module handles the modification of diff html generated by difflib for AStyle Tool purpose."

def modifyDiffHTML(strHTML, fname):
    marker = '<table class="diff" summary="Legends">'
    newHTML = strHTML
    newHTML = newHTML.replace(newHTML[newHTML.find(marker):],'')
    newHTML = newHTML.replace('span class="diff_add"', 'span style="background-color:#aaffaa;"')
    newHTML = newHTML.replace('span class="diff_chg"', 'span style="background-color:#ffff77;"')
    newHTML = newHTML.replace('span class="diff_sub"', 'span style="background-color:#ffaaaa;"')
    newHTML = newHTML.replace('class="diff_add"', 'bgcolor=#aaffaa')
    newHTML = newHTML.replace('class="diff_chg"', 'bgcolor=#ffff77')
    newHTML = newHTML.replace('class="diff_sub"', 'bgcolor=#ffaaaa')
    newHTML = newHTML.replace('class="diff_next"', 'bgcolor=#c0c0c0')
    newHTML = newHTML.replace('class="diff_header"', 'bgcolor=#e0e0e0')
    newHTML = newHTML.replace('class="diff"', 'style="font-family:Monaco; font-size:10pt; text-aligh:right;"')

    origList = []
    convList = []
    wc = re.findall('[\w\W]*?</td>', newHTML)

    header = wc[0][:wc[0].find(re.findall('<td.*</td>', wc[0])[0])]
    header = header.replace('<body>', '<body style="background-color:#eaeaea;">')
    for i in xrange(len(wc)):
        if i%6 < 3: flag = 'orig'
        else: flag = 'conv'
        if not i%3:
            if i==0:
                origList.append(header)
                convList.append(header)
            try:
                if 'orig'==flag:
                    origList.append(wc[i][:wc[i].find(re.findall('<td.*</td>', wc[i])[0])])
                else:
                    convList.append(wc[i][:wc[i].find(re.findall('<td.*</td>', wc[i])[0])])
            except:
                print i, wc[i]
                if 'orig'==flag:
                    origList.append(wc[i])
                else:
                    if 5==(i%6): convList.append(wc[i] + '</tr>')
                    else: convList.append(wc[i])
        else:
            if (1==(i%6) or 4==(i%6)):
                tmp = wc[i]
                reg = re.findall('>[0-9]*?<',tmp)[0]
                tmp = tmp.replace(reg, '><font color="green">' + reg[1:-1] + '</font><')
                wc[i] = tmp

            if 'orig'==flag:
                origList.append(wc[i])
            else:
                if 5==(i%6): convList.append(wc[i] + '</tr>')
                else: convList.append('<tr>' + wc[i])

    origList.append('</tr></table></body></html>')
    convList.append('</tr></table></body></html>')

    f_orig = file(fname[:fname.rindex('.')]+'_orig.html', 'w')
    f_conv = file(fname[:fname.rindex('.')]+'_conv.html', 'w')

    f_orig.write(''.join(origList))
    f_conv.write(''.join(convList))
    f_orig.close()
    f_conv.close()

    return fname


if __name__ == '__main__':
    main()